;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        Buffer-menu-delete
        abbrev-prefix-mark
        beginning-of-buffer
        beginning-of-line-or-indentation
        dabbrev-expand
        downcase-region
        duplicate-line-or-region
        electric-newline-and-maybe-indent
        elpy-nav-backward-indent
        elpy-nav-indent-shift-left
        elpy-nav-indent-shift-right
        end-of-visual-line
        fill-paragraph
        haskell-indentation-common-electric-command
        haskell-interactive-mode-space
        haskell-process-load-file
        indent-for-tab-command
        indent-rigidly-left
        intero-repl-eval-decl
        kill-region
        markdown-cycle
        markdown-electric-backquote
        markdown-outdent-or-delete
        markdown-shifttab
        my-eval-decl
        org-beginning-of-line
        org-end-of-line
        org-force-self-insert
        org-return-indent
        org-self-insert-command
        org-yank
        phi-search
        phi-search-backward
        sh-assignment
        undefined
        upcase-region
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        ahs-backward
        ahs-forward
        artist-previous-line
        counsel-M-x
        counsel-locate
        counsel-projectile-ag
        dired
        eval-print-last-sexp
        handle-switch-frame
        hydra-hydra/body
        hydra-hydra/nil
        indent-rigidly
        ivy-end-of-buffer
        list-directory
        mouse-drag-vertical-line
        overwrite-mode
        swiper
        swiper-mc
        wgrep-finish-edit
        ))
